{
 "title": "User Impact - __DEPLOY_ENV__",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Gorouter requests/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(firehose_counter_event_gorouter_responses_total[2m]))",
     "legendFormat": "All Responses"
    },
    {
     "expr": "sum(rate(firehose_counter_event_gorouter_responses_4_xx_total[2m]))",
     "legendFormat": "4xx Responses"
    },
    {
     "expr": "sum(rate(firehose_counter_event_gorouter_responses_5_xx_total[2m]))",
     "legendFormat": "5xx Responses"
    }
   ]
  },
  {
   "title": "API requests/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(firehose_value_metric_cc_http_status_2_xx[2m]))",
     "legendFormat": "2xx Responses"
    },
    {
     "expr": "sum(rate(firehose_value_metric_cc_http_status_4_xx[2m]))",
     "legendFormat": "4xx Responses"
    },
    {
     "expr": "sum(rate(firehose_value_metric_cc_http_status_5_xx[2m]))",
     "legendFormat": "5xx Responses"
    }
   ]
  },
  {
   "title": "Application Instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(firehose_value_metric_bbs_lr_ps_running)",
     "legendFormat": "LRPsRunning"
    },
    {
     "expr": "max(firehose_value_metric_bbs_lr_ps_desired)",
     "legendFormat": "LRPsDesired"
    }
   ]
  },
  {
   "title": "UAA requests/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(firehose_value_metric_uaa_requests_global_status_2_xx_count[2m]))",
     "legendFormat": "2xx Responses"
    },
    {
     "expr": "sum(rate(firehose_value_metric_uaa_requests_global_status_4_xx_count[2m]))",
     "legendFormat": "4xx Responses"
    },
    {
     "expr": "sum(rate(firehose_value_metric_uaa_requests_global_status_5_xx_count[2m]))",
     "legendFormat": "5xx Responses"
    }
   ]
  },
  {
   "title": "Cell Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "bosh_job_mem_percent{bosh_job_name=\"diego-cell\"}",
     "legendFormat": "{{bosh_job_id}} ({{bosh_job_ip}})"
    }
   ]
  },
  {
   "title": "CloudController Job Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(firehose_value_metric_cc_job_queue_length_total)",
     "legendFormat": "CC Job Queue Length"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"}) or vector(0)"
    }
   ]
  }
 ]
}